apiVersion:v1
kind:Secret
metadata:
   name: mongo-secret
data:
   admin-username: dXNlcm5hbWUK
   admin-password: cGFzc3dvcmQK

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mongo-data
data:
  databse_url: mongodb-service
   
